# Generated by Django 4.2.7 on 2026-08-19 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('Phishing', 'Phishing'), ('Malware', 'Malware'), ('Ransomware', 'Ransomware'), ('DDoS', 'DDoS'), ('Insider Threat', 'Insider Threat'), ('Data Breach', 'Data Breach'), ('Unauthorized Access', 'Unauthorized Access'), ('Social Engineering', 'Social Engineering')], max_length=50, null=True)),
                ('severity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=30)),
                ('ml_classification_status', models.CharField(choices=[('pending', 'Pending Classification'), ('classified', 'Classified'), ('failed', 'Classification Failed')], db_index=True, default='pending', max_length=20)),
                ('ml_classification_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('analyst', models.ForeignKey(db_column='analyst_id', on_delete=django.db.models.deletion.PROTECT, related_name='investigation_notes', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Investigation Note',
                'verbose_name_plural': 'Investigation Notes',
                'db_table': 'investigation_notes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='incident_attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.incident')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Attachment',
                'verbose_name_plural': 'Incident Attachments',
                'db_table': 'incident_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='idx_incident_status'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity'], name='idx_incident_severity'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['category'], name='idx_incident_category'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-created_at'], name='idx_incident_created'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['ml_classification_status'], name='idx_incident_ml_status'),
        ),
    ]
