# Generated by Django 4.2.7 on 2026-08-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='indicators_of_compromise',
            field=models.TextField(blank=True, default=''),
        ),
    ]
