# Generated by Django 4.2.7 on 2026-08-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_category', models.CharField(max_length=50)),
                ('predicted_severity', models.CharField(max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('action_recommendations', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(default='', max_length=100)),
                ('is_trained_model', models.BooleanField(default=False)),
                ('analyst_override_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'verbose_name_plural': 'ML Predictions',
                'db_table': 'ml_predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
